### ISSUE TITLE
Full-Schedule-Scan CloudFormation readme update and missing version.json

### ISSUE THREAD

**Issue by JustinDPerkins** [trendmicro/cloudone-filestorage-plugins#121]
## Plugin Path:
https://github.com/trendmicro/cloudone-filestorage-plugins/tree/master/scan-triggers/aws-python-bucket-full-and-scheduled-scan

## Describe the bug:
- The full scan plugin when deployed using CloudFormation does not scan objects. You receive and error when performing the manual invoke.

- In addition, the readme conflicts with the Cloudformation deployment. Different names for the functions. The Readme aligns to the SAR deployment.

## To reproduce:

- Deploy Full Scan via CloudFormation
- Use event test JSON

## Expected behavior:

- Scan all objects in bucket successfully.

## Screenshots:

- Via CFT - resource names
![cft](https://user-images.githubusercontent.com/60413733/218783598-5752c206-2abd-4700-b60e-5a3e21b6313d.jpg)

- Via SAR - resource names
![sar](https://user-images.githubusercontent.com/60413733/218783642-334ded9e-a97b-4d66-8e89-8cee38c726ff.jpg)

## Lambda Test execution details:
```
# test event JSON:
{
  "key1": "value1",
  "key2": "value2",
  "key3": "value3"
}
```
---

```
# Execution Response:
Response
{
  "errorMessage": "'bucket'",
  "errorType": "KeyError",
  "requestId": "89c8c76c-2820-42c5-bf51-59312f288843",
  "stackTrace": [
    "  File \"/var/task/index.py\", line 108, in lambda_handler\n    bucket = event['bucket']\n"
  ]
}

Function Logs
scanner queue URL: https://sqs.us-east-1.amazonaws.com/024368254241/The-FSS-Scanner-ScannerQueue-Xlzp8x9VX1Uu
scanner queue region: us-east-1
scanner queue endpoint URL: https://sqs.us-east-1.amazonaws.com
report object key: False
failed to get version: [Errno 2] No such file or directory: 'version.json'
START RequestId: 89c8c76c-2820-42c5-bf51-59312f288843 Version: $LATEST
[ERROR] KeyError: 'bucket'
Traceback (most recent call last):
  File "/var/task/index.py", line 108, in lambda_handler
    bucket = event['bucket']END RequestId: 89c8c76c-2820-42c5-bf51-59312f288843
REPORT RequestId: 89c8c76c-2820-42c5-bf51-59312f288843	Duration: 12.21 ms	Billed Duration: 13 ms	Memory Size: 128 MB	Max Memory Used: 68 MB	Init Duration: 403.03 ms

Request ID
89c8c76c-2820-42c5-bf51-59312f288843
```

**Comment by jack-c-tang** [comment]
@JustinDPerkins, the readme supposedly has been fixed in the PR. Would you please check whether the issue persists?

**Comment by JustinDPerkins** [comment]
LGTM
