### ISSUE TITLE
Enable VPC Support in Promote/Quarantine Plugin for AWS Serverless Repo

### ISSUE THREAD

**Issue by modomodo** [trendmicro/cloudone-filestorage-plugins#122]
With C1FSS supporting VPCs https://cloudone.trendmicro.com/docs/file-storage-security/aws-vpc-proxy/ It would be great if the promote/quarantine plugin had the same feature

Manually tried this by doing the manual method and specified subnet/security group and the function worked - it just now needs to be available in the SAM Template for easier/quicker deployment and the AWS Serverless Repo [serverlessrepo.aws.amazon.com/applications/us-east-1/415485722356/cloudone-filestorage-plugin-action-promote-or-quarantine ](https://serverlessrepo.aws.amazon.com/applications/us-east-1/415485722356/cloudone-filestorage-plugin-action-promote-or-quarantine)

**Comment by jack-c-tang** [comment]
It's supported now.

**Comment by jack-c-tang** [comment]
It's supported now.
