### ISSUE TITLE
Support prefix in promote or quarantine

### ISSUE THREAD

**Issue by felipecosta09** [trendmicro/cloudone-filestorage-plugins#127]
Customers want to be able to use custom prefixes in the promote and quarantine buckets, e.g send bad files to the prefix `bad` and good files to the prefix `good`.

https://github.com/trendmicro/cloudone-filestorage-plugins/tree/master/post-scan-actions/aws-python-promote-or-quarantine

## Problem to solve

Today we don't have a way to customize how the file will be moved, we simply get the same bucket and key as the original bucket and pass that to the promote or quarantine buckets.

## Proposed solution

Add support to a custom prefix in the promote and quarantine plugin, preferentially when we are deploying the stack, like that:

![image](https://user-images.githubusercontent.com/33869171/231871768-b259ca2e-bcc8-41b9-b93a-a9e2b932a366.png)

Or even using a new parameter for each bucket so we can add any prefix.

**Comment by jack-c-tang** [comment]
Hi @felipecosta09, is there any reason they don't use two buckets to achieve that? Then the control to the promote/quarantine buckets can be defined separately to not access bad objects accidentally.

**Comment by felipecosta09** [comment]
> Hi @felipecosta09, is there any reason they don't use two buckets to achieve that? Then the control to the promote/quarantine buckets can be defined separately not to access bad objects accidentally.

No particular reason, it is just the way that prefers to set up without having additional buckets. I was able to make a modification on the Python file for the plugin, the changes go from line 187 up to 207:

```python
# That's the only change, in the case is "malicious" it's going to add the "bad" prefix to the object_key, and in the case is not, add the prefix "good"
        if scan_result == "malicious":
            copy_object(
                source_bucket=src_bucket,
                dest_bucket=dst_bucket,
                source_key=object_key,
                dest_key="bad/"+object_key,
                tags=tags,
                metadata=metadata,
                acl=acl,
            )
        else:
            copy_object(
                source_bucket=src_bucket,
                dest_bucket=dst_bucket,
                source_key=object_key,
                dest_key="good/"+object_key,
                tags=tags,
                metadata=metadata,
                acl=acl,
            )
```

I honestly don't know if this way would be easier or to set up 2 buckets. In case moving this way it will need additional modifications in the CFN like parameters to define the prefix instead of hardcoded like I did.

**Comment by jack-c-tang** [comment]
Of course this can be done. However, given that the promote bucket should always keep good (promoted) objects, I feel like this is not a general use case to put good and bad files in the same bucket.

**Comment by felipecosta09** [comment]
Make sense!
