### ISSUE TITLE
!!! emergency !!! not supported KMS on S3

### ISSUE THREAD

**Issue by jawahiko** [trendmicro/cloudone-filestorage-plugins#144]
### Discussed in https://github.com/trendmicro/cloudone-filestorage-plugins/discussions/143

<div type='discussions-op-text'>

<sup>Originally posted by **jawahiko** August  4, 2023</sup>
表題の通りです。
KMS設定されたS3には隔離機能が働きません。。。DEVでは動作していたのに本番では動作しなくて困っていたところ、KMS暗号化がかかったS3では動作しないLambda関数になっていたことが発覚しました。。
python修正を試みてますが出来ず。。。急ぎ対応をお願いしたく。。

As the title says.
Quarantine function does not work for S3 with KMS settings. . . It worked in DEV, but when I was in trouble because it didn't work in production, I discovered that the Lambda function didn't work in S3 with KMS encryption. .
I'm trying to fix python, but I can't. . . I would like to ask for your urgent response. .</div>

**Comment by jack-c-tang** [comment]
Hi @jawahiko ,
This requires additional actions to allow the quarantine and promote lambda execution role to use the key. Please see https://github.com/trendmicro/cloudone-filestorage-plugins/issues/85 for reference.

**Comment by jack-c-tang** [comment]
It's supported now.
