### ISSUE TITLE
Missing steps in azure-python-promote-or-quarantine for publishing the Azure function

### ISSUE THREAD

**Issue by Chiragkansara** [trendmicro/cloudone-filestorage-plugins#149]
Hello,

In the post-scan-actions/azure-python-promote-or-quarantine there are missing steps for publishing the Azure function. After deploying the function files will not be moved to the promote or quarantine bucket unless the function is published

**Comment by jack-c-tang** [comment]
Hi @Chiragkansara , the plugin now is deployed through deployment template. There is no "publish step" in this deployment model.

**Comment by Chiragkansara** [comment]
Hi @jack-c-tang , In the link below, I am unable to see an option in Azure for a deployment template for the promote-or-quarantine plug-in. Is it located else where?  https://github.com/trendmicro/cloudone-filestorage-plugins/tree/master/post-scan-actions/azure-python-promote-or-quarantine
