### ISSUE TITLE
Implement proper object promotion workflow after successful tagging

### ISSUE THREAD

**Issue by marinpurgar** [trendmicro/cloudone-filestorage-plugins#43]
# post-scan-actions/aws-python-promote-or-quarantine

## Problem to solve

Currently the Promote or Quarantine Lambda Function is waiting 15 seconds before starting to promote / quarantine S3 Objects. The wait is there in order to assure that the Tagging Post Scan Action is done and there is no race condition between the two Post Scan Actions. This goes against the fundamentals of the serverless architecture.

The issues with this approach are:
- there is no guarantee that the Tagging Post Scan Action is going to be finished in 15 seconds. AWS S3 does not guarantee the maximum execution time of the tagging action.
- there is a 15 seconds penalty in the lambda execution which unnecessary prolongs the time of the whole scan workflow
- those (unnecessary) 15 seconds are billed by AWS

## Proposed solution

Change the architecture of the Storage Stack in order to ensure the tagging of the S3 Object is done before sending the message to the Post Scan SNS Topic.

The tagging shouldn't be executed as the Post Scan Action subscribed to the Scan Result SNS Topic but as a separate action before the message is sent to the Scan Result SNS Topic. This would ensure that the Post Scan Actions are triggered after the tagging is done.

## Alternatives

Interim solutions not involving changing the Storage Stack:
- in the loop check if the S3 Object has been tagged by the Tagging Post Scan Action and proceed when tagging is done
- or, check if the S3 Object has been tagged by the Tagging Post Scan Action and re-queue Lambda Invocation with the delay

## Additional context

Commit which introduced 15 seconds wait: https://github.com/trendmicro/cloudone-filestorage-plugins/commit/0de1ebcaf41472790f94ea622adcaa0d99141f31#diff-6cad5d9dc88c1e7f608e9a5d3ba739020073f986af54e4ad284e34156ad05ee1
Pull Request: https://github.com/trendmicro/cloudone-filestorage-plugins/pull/12

**Comment by carpusherw** [comment]
Hi @marinpurgar ,
The proposed solution is not ideal because of the following.

- We don't expect the tag to be a required output for all users. Some users would only need the scan result from the SNS topic.
- Making tagging a synchronous action will extend latency of scan result form the SNS topic.

In addition to your alternatives, would you also accept that this plugin directly add the same tagging to the destination object? It would be much simpler but make it like a "promote-or-quarantine and then tag" plugin.

**Comment by marinpurgar** [comment]
The tagging of the S3 Object in the Promote or Quarantine Post Scan Action is acceptable. As long as the 15 seconds wait is removed.
Would the tagging information be the same as from the Tagging Post Scan Action?

**Comment by carpusherw** [comment]
It could be the same. But as I mentioned above, changes in the tagging post-scan action may have delay to the promote or quarantine plugin.
