### ISSUE TITLE
Cloud Conformity API does not exist anymore

### ISSUE THREAD

**Issue by perezxavier** [trendmicro/cloudone-filestorage-plugins#81]
# <PATH_TO_THE_PLUGIN>

## Problem to solve

 Just a quick message to tell you that the prerequisites seem to be not up to date because for Cloud Conformity, we have to do it directly in the Cloud One Dashboard
![image](https://user-images.githubusercontent.com/84787994/168286135-7fc97f19-3d00-495b-89a5-b39eda96b969.png)

## Proposed solution

 updating with the new methodology
![image](https://user-images.githubusercontent.com/84787994/168286242-c321b27d-0531-4b19-9b58-62c3137a2a56.png)

**Comment by chenjill** [comment]
Hi @perezxavier, thank you! We will start to change the description of the conformity plugin.

**Comment by perezxavier** [comment]
Very good!
Thanks guys
