### ISSUE TITLE
Issue when using KMS Keys

### ISSUE THREAD

**Issue by fafiorim** [trendmicro/cloudone-filestorage-plugins#85]
#post-scan-actions/aws-python-promote-or-quarantine

## Problem to solve

By default, the plugin will not consider any KMS key. So, after the deployment in an s3 bucket that is using a KMS key for encryption the plugin will not work until manually adding the "PromoteOrQuarantineLambdaRole" IAM Role as a user in the Keys in use for the Bucket, SQS, and SNS.

## Proposed solution

Request the Keys as parameters in the CloudFormation Template to add the "PromoteOrQuarantineLambdaRole" IAM Role as a user in the KMS Keys. 

## Alternatives

Add a documentation topic describing the action needed. So, that is necessary to add the  "PromoteOrQuarantineLambdaRole" IAM Role as a user in the KMS Keys

## Additional context

![CloudFormationTemplate](https://user-images.githubusercontent.com/12775199/175109914-9a73421d-e406-49a5-9d02-044cafc72dc5.png)
![KMS_keys](https://user-images.githubusercontent.com/12775199/175109913-14093369-e189-40fe-958d-f0280ac48799.png)
![KMS_Key_add_user](https://user-images.githubusercontent.com/12775199/175109910-0e632df2-f5c3-4b26-9dbd-6b9b7a6b61d4.png)

**Comment by felipecosta09** [comment]
@jack-c-tang any updates here?

**Comment by carpusherw** [comment]
It's not a good practice to update resources outside of the stack. I would suggest the alternative solution to update the document.

**Comment by felipecosta09** [comment]
@fafiorim any comments on that?

**Comment by fafiorim** [comment]
Hi @felipecosta09 and @carpusherw. As it isn't a good practice to update resources outside the stack, let move to the alternative solution that is the documentation of the additional steps needed.

**Comment by felipecosta09** [comment]
@jack-c-tang I think we can close this issue as `resolved`

**Comment by jack-c-tang** [comment]
> @jack-c-tang I think we can close this issue as `resolved`

I thought the document still needs to be updated?

**Comment by felipecosta09** [comment]
@fafiorim, take a look at PR #139, as soon is merged, it should fix your issue.

**Comment by jack-c-tang** [comment]
It's supported now.
